### ISSUE TITLE
🪲May Need to Change .env File

### ISSUE THREAD

**Issue by mxu4321** [rbkeyes/group-project-2#21]
If by completing the project we can't figure the ignore & .env, let's just do the change on github repo for the .env to ⤵️, and pull main branch again
```
DB_NAME='product_db'
DB_USER=''
DB_PASSWORD=''
```

**Comment by rbkeyes** [comment]
cleared cache and latest pull request now says .env has been deleted (it's still showing locally for me though, which means it's now being ignored properly). Good catch Meng!

In case we run into this again, just run
`git rm --cached .env` in the terminal, then git add and git commit
